version: 0.0
os: linux
files:
  - source: .
    destination: /home/ubuntu/rateyourlandlord
hooks:
  ApplicationStop:
  - location: scripts/application_stop.sh
    timeout: 300
    runas: ubuntu
  ApplicationStart:
  - location: scripts/application_start.sh
    timeout: 300
    runas: ubuntu
Github uses aws.yml file to manage Github actions.