name: AWS Deploy 
on:
  push:

    branches: [ master ]

jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout to repo 
        uses: actions/checkout@v2name: AWS Deploy 
on:
  push:

    branches: [ master ]

jobs:

  deploy:
  

    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     node-version: [12.x]
    #     app-name: ['your-codedeploy-application']
    #     deployment-group: ['your-codedeploy-deploy-group']
    #     repo: ['username/repository-name']
        
    steps:
    #   - uses: actions/checkout@v2
      
    #   - name: Use Node.js ${{ matrix.node-version }}
    #     uses: actions/setup-node@v1
    #     with:
    #       node-version: ${{ matrix.node-version }}
          
    #   - name: Install dependencies
    #     run: npm install
      
    #   - name: Build app
    #     run: npm run build
      - name: Checkout to repo 
        uses: actions/checkout@v2
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2


      - name: Create CodeDeploy Deployment
        id: deploy
        run: |
          aws deploy create-deployment \
            --application-name rateyourstudenthouse_application \
            --deployment-group-name rateyourstudenthouse_deployment \
            --deployment-config-name CodeDeployDefault.OneAtATime \
            --github-location repository=${{ github.repository }},commitId=${{ github.sha }}


      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2


      - name: Create CodeDeploy Deployment
        id: deploy
        run: |
          aws deploy create-deployment \
            --application-name rateyourstudenthouse_application \
            --deployment-group-name rateyourstudenthouse_deployment \
            --deployment-config-name CodeDeployDefault.OneAtATime \
            --github-location repository=${{ github.repository }},commitId=${{ github.sha }}
