name: AWS Deploy 
on:
  push:

    branches: [ master ]

jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout to repo 
        uses: actions/checkout@v2
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2b
          
          instance-ids: ${{ secrets.INSTANCE_ID  }}
          comment: Deploy the master branch
          working-directory: /home/ubuntu/rateyourlandlord
          script: sh scripts/deploy_application.sh
    